# Generated by Django 2.2.4 on 2020-04-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200416_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='dojo_id',
        ),
    ]
