# Generated by Django 3.0.4 on 2020-04-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=500, max_length=500),
            preserve_default=False,
        ),
    ]
