# Generated by Django 3.0.5 on 2020-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(max_length=100),
        ),
    ]
