# Generated by Django 3.0.5 on 2020-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200428_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
